# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('status', django_fsm.FSMField(choices=[('received', 'received'), ('in_progress', 'in_progress'), ('sent', 'sent'), ('success', 'success'), ('Failed', 'Failed'), ('failed', 'failed')], default='received', max_length=255, protected=True, verbose_name='Status')),
                ('names', models.CharField(blank=True, max_length=255, null=True, verbose_name='Names')),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update Date')),
                ('message_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'SMS Recipient',
                'verbose_name_plural': 'SMS Recipients',
            },
        ),
        migrations.CreateModel(
            name='SmsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Update Date')),
                ('response', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS Transaction',
                'verbose_name_plural': 'SMS Transactions',
            },
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender')),
                ('to', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='smsrecipient',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_transactions', to='core.SmsTransaction'),
        ),
    ]
