# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='message',
            field=models.TextField(blank=True, default='The quick brown fox jumped over the old fence', null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='sender',
            field=models.CharField(blank=True, choices=[('Tumacredo', 'Tumacredo'), ('AFRICASTKNG', 'AFRICASTKNG')], max_length=255, null=True, verbose_name='Sender'),
        ),
    ]
